### ISSUE TITLE
我启动成功了，但是连接不上，好像需要（时间戳：token）

### ISSUE THREAD

**Issue by zjqwll** [root-wyj/springboot_im#1]
我启动成功了，但是连接不上，好像需要（时间戳：token）
作者没有对页面端的参数说明

**Comment by root-wyj** [comment]
不好意思哈。

当你启动服务成功之后，访问 “http://localhost:8080/index2.html”。

可以看到有一个Connect按钮，这里需要填写token。下面说一下，token的获取方式

需要请求一下这个接口：“http://localhost:8080/login”。 header里面的content-type=application/json;charset=utf-8. 参数以json的形式放入request的body里面，我这里用的工具是Postman，请求和返回值如下：
![token](https://github.com/root-wyj/springboot_im/blob/master/img/postman1.png)

将返回的token 直接复制到 connect 按钮前面的输入框里面，点击connect 就可以了。

还需要注意，将数据库的环境配置好，数据库的名字是imdb1user。创建好数据库之后，可以运行clone下来的imdb1user.sql吧数据导入。

ps：我也会修改下代码，把connect的步骤简化，你也可以重新clone一个新的版本。

**Comment by zjqwll** [comment]
很感谢您的耐心回复，我这几天也仔细研究了您的代码，您的说的步骤也基本理顺了，代码写的非常棒，已点赞！



85583755@qq.com
 
发件人： root-wyj
发送时间： 2018-02-06 16:02
收件人： root-wyj/springboot_im
抄送： zjqwll; Author
主题： Re: [root-wyj/springboot_im] 我启动成功了，但是连接不上，好像需要（时间戳：token） (#1)
不好意思哈。
当你启动服务成功之后，访问 “http://localhost:8080/index2.html”。
可以看到有一个Connect按钮，这里需要填写token。下面说一下，token的获取方式
需要请求一下这个接口：“http://localhost:8080/login”。 header里面的content-type=application/json;charset=utf-8. 参数以json的形式放入request的body里面，我这里用的工具是Postman，请求和返回值如下：
将返回的token 直接复制到 connect 按钮前面的输入框里面，点击connect 就可以了。
还需要注意，将数据库的环境配置好，数据库的名字是imdb1user。创建好数据库之后，可以运行clone下来的imdb1user.sql吧数据导入。
ps：我也会修改下代码，把connect的步骤简化，你也可以重新clone一个新的版本。

**Comment by root-wyj** [comment]
互相进步

**Comment by zjqwll** [comment]
你好，朋友，你的代码写相当不错，对性能，并发方面做了处理，但是我觉得1、有些东西为什么不用redis，后期如果socket集群，怎么处理？2、有些封装的类比较杂，能清晰化处理吗



85583755@qq.com
 
发件人： root-wyj
发送时间： 2018-02-06 16:02
收件人： root-wyj/springboot_im
抄送： zjqwll; Author
主题： Re: [root-wyj/springboot_im] 我启动成功了，但是连接不上，好像需要（时间戳：token） (#1)
不好意思哈。
当你启动服务成功之后，访问 “http://localhost:8080/index2.html”。
可以看到有一个Connect按钮，这里需要填写token。下面说一下，token的获取方式
需要请求一下这个接口：“http://localhost:8080/login”。 header里面的content-type=application/json;charset=utf-8. 参数以json的形式放入request的body里面，我这里用的工具是Postman，请求和返回值如下：
将返回的token 直接复制到 connect 按钮前面的输入框里面，点击connect 就可以了。
还需要注意，将数据库的环境配置好，数据库的名字是imdb1user。创建好数据库之后，可以运行clone下来的imdb1user.sql吧数据导入。
ps：我也会修改下代码，把connect的步骤简化，你也可以重新clone一个新的版本。

**Comment by zjqwll** [comment]
你好，请问RoomContext这个类怎么理解，为什么不用redis代替？有什么好处，没看明白。


85583755@qq.com
 
发件人： root-wyj
发送时间： 2018-02-06 16:02
收件人： root-wyj/springboot_im
抄送： zjqwll; Author
主题： Re: [root-wyj/springboot_im] 我启动成功了，但是连接不上，好像需要（时间戳：token） (#1)
不好意思哈。
当你启动服务成功之后，访问 “http://localhost:8080/index2.html”。
可以看到有一个Connect按钮，这里需要填写token。下面说一下，token的获取方式
需要请求一下这个接口：“http://localhost:8080/login”。 header里面的content-type=application/json;charset=utf-8. 参数以json的形式放入request的body里面，我这里用的工具是Postman，请求和返回值如下：
将返回的token 直接复制到 connect 按钮前面的输入框里面，点击connect 就可以了。
还需要注意，将数据库的环境配置好，数据库的名字是imdb1user。创建好数据库之后，可以运行clone下来的imdb1user.sql吧数据导入。
ps：我也会修改下代码，把connect的步骤简化，你也可以重新clone一个新的版本。

**Comment by zhukovaskychina** [comment]
你仔细看代码





| |
朱可夫
邮箱：zhukovasky@163.com
|

签名由 网易邮箱大师 定制

在2018年03月30日 09:30，隐者 写道：
你好，请问RoomContext这个类怎么理解，为什么不用redis代替？有什么好处，没看明白。


85583755@qq.com

发件人： root-wyj
发送时间： 2018-02-06 16:02
收件人： root-wyj/springboot_im
抄送： zjqwll; Author
主题： Re: [root-wyj/springboot_im] 我启动成功了，但是连接不上，好像需要（时间戳：token） (#1)
不好意思哈。
当你启动服务成功之后，访问 “http://localhost:8080/index2.html”。
可以看到有一个Connect按钮，这里需要填写token。下面说一下，token的获取方式
需要请求一下这个接口：“http://localhost:8080/login”。 header里面的content-type=application/json;charset=utf-8. 参数以json的形式放入request的body里面，我这里用的工具是Postman，请求和返回值如下：
将返回的token 直接复制到 connect 按钮前面的输入框里面，点击connect 就可以了。
还需要注意，将数据库的环境配置好，数据库的名字是imdb1user。创建好数据库之后，可以运行clone下来的imdb1user.sql吧数据导入。
ps：我也会修改下代码，把connect的步骤简化，你也可以重新clone一个新的版本。

**Comment by zjqwll** [comment]
我看了好几遍，没看懂，跳来跳去，思路感觉非常不清晰，不知道怎么的，RoomContext有别的写法吗，redis能替代吗


85583755@qq.com
 
发件人： zhukovaskychina
发送时间： 2018-03-30 09:31
收件人： root-wyj/springboot_im
抄送： 隐者; Author
主题： Re: [root-wyj/springboot_im] 我启动成功了，但是连接不上，好像需要（时间戳：token） (#1)
你仔细看代码





| |
朱可夫
邮箱：zhukovasky@163.com
|

签名由 网易邮箱大师 定制

在2018年03月30日 09:30，隐者 写道：
你好，请问RoomContext这个类怎么理解，为什么不用redis代替？有什么好处，没看明白。


85583755@qq.com

发件人： root-wyj
发送时间： 2018-02-06 16:02
收件人： root-wyj/springboot_im
抄送： zjqwll; Author
主题： Re: [root-wyj/springboot_im] 我启动成功了，但是连接不上，好像需要（时间戳：token） (#1)
不好意思哈。
当你启动服务成功之后，访问 “http://localhost:8080/index2.html”。
可以看到有一个Connect按钮，这里需要填写token。下面说一下，token的获取方式
需要请求一下这个接口：“http://localhost:8080/login”。 header里面的content-type=application/json;charset=utf-8. 参数以json的形式放入request的body里面，我这里用的工具是Postman，请求和返回值如下：
将返回的token 直接复制到 connect 按钮前面的输入框里面，点击connect 就可以了。
还需要注意，将数据库的环境配置好，数据库的名字是imdb1user。创建好数据库之后，可以运行clone下来的imdb1user.sql吧数据导入。
ps：我也会修改下代码，把connect的步骤简化，你也可以重新clone一个新的版本。
